name: Deploy Chatbot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/apps/chatbot
          git fetch origin
          git reset --hard origin/master
          cd base-meta-json
          npm install --legacy-peer-deps
